name: deepbc
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - comm=0.1.4
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libcxx=16.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.1.4
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.40
  - prompt_toolkit=3.0.40
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python_abi=3.11
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - traitlets=5.13.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.9
  - xz=5.4.2
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip
  - pip:
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - contourpy==1.1.0
    - cycler==0.11.0
    - debugpy==1.8.0
    - filelock==3.12.3
    - fonttools==4.42.1
    - frozenlist==1.4.0
    - fsspec==2023.9.0
    - idna==3.4
    - jinja2==3.1.2
    - jupyter-core==5.5.0
    - kiwisolver==1.4.5
    - lightning-utilities==0.9.0
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - networkx==3.1
    - normflows==1.7.2
    - numpy==1.25.2
    - packaging==23.1
    - pandas==2.1.0
    - pillow==10.0.0
    - pip==23.2.1
    - psutil==5.9.5
    - pyparsing==3.0.9
    - pytorch-lightning==2.0.8
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - requests==2.31.0
    - seaborn==0.12.2
    - setuptools==68.0.0
    - sympy==1.12
    - torch==2.0.1
    - torchmetrics==1.1.1
    - torchvision==0.15.2
    - tornado==6.3.3
    - tqdm==4.66.1
    - typing-extensions==4.7.1
    - tzdata==2023.3
    - urllib3==2.0.4
    - wheel==0.38.4
    - yarl==1.9.2