from setuptools import setup, find_packages

print(find_packages(where='src'))

setup(
    name='deepbc',
    version='1.0.1',
    url=None,
    author='Klaus-Rudolf Kladny',
    description='Deep Backtracking Counterfactuals',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    install_requires=[
        'aiohttp==3.8.5',
        'aiosignal==1.3.1',
        'async-timeout==4.0.3',
        'attrs==23.1.0',
        'certifi==2023.7.22',
        'charset-normalizer==3.2.0',
        'contourpy==1.1.0',
        'cycler==0.11.0',
        'debugpy==1.8.0',
        'filelock==3.12.3',
        'fonttools==4.42.1',
        'frozenlist==1.4.0',
        'fsspec==2023.9.0',
        'idna==3.4',
        'jinja2==3.1.2',
        'jupyter-core==5.5.0',
        'kiwisolver==1.4.5',
        'lightning-utilities==0.9.0',
        'markupsafe==2.1.3',
        'mpmath==1.3.0',
        'multidict==6.0.4',
        'networkx==3.1',
        'normflows==1.7.2',
        'numpy==1.25.2',
        'packaging==23.1',
        'pandas==2.1.0',
        'psutil==5.9.5',
        'pyparsing==3.0.9',
        'pytorch-lightning==2.0.8',
        'pytz==2023.3.post1',
        'pyyaml==6.0.1',
        'pyzmq==25.1.1',
        'requests==2.31.0',
        'sympy==1.12',
        'torch==2.0.1',
        'torchmetrics==1.1.1',
        'tornado==6.3.3',
        'tqdm==4.66.1',
        'typing-extensions==4.7.1',
        'urllib3==2.0.4',
        'wheel==0.38.4',
        'yarl==1.9.2',
    ],
)